# permissions for end users to view kubeadmcontrolplanetemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeadmcontrolplanetemplate-viewer-role
rules:
- apiGroups:
  - controlplane.controlplane.kubekey.kubesphere.io
  resources:
  - kubeadmcontrolplanetemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - controlplane.controlplane.kubekey.kubesphere.io
  resources:
  - kubeadmcontrolplanetemplates/status
  verbs:
  - get
