# permissions for end users to view controlplanes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controlplane-viewer-role
rules:
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - controlplanes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - controlplanes/status
  verbs:
  - get
