# permissions for end users to edit kubeadmconfigtemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeadmconfigtemplate-editor-role
rules:
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - kubeadmconfigtemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - kubeadmconfigtemplates/status
  verbs:
  - get
