# permissions for end users to view kubeadmconfigtemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeadmconfigtemplate-viewer-role
rules:
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - kubeadmconfigtemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - kubeadmconfigtemplates/status
  verbs:
  - get
