# permissions for end users to edit machinedeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machinedeployment-editor-role
rules:
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - machinedeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - machinedeployments/status
  verbs:
  - get
