# permissions for end users to edit machinesets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machineset-editor-role
rules:
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - machinesets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - machinesets/status
  verbs:
  - get
