
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - auditing.kubesphere.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - autoscaling
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - certificates.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - cluster.kubesphere.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - config.istio.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kubefed.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - devops.kubesphere.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - events.kubesphere.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - extensions
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - iam.kubesphere.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - installer.kubesphere.io
  resources:
  - clusterconfigurations
  verbs:
  - '*'
- apiGroups:
  - jaegertracing.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - addons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - addons/finalizers
  verbs:
  - update
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - addons/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - controlplanes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - controlplanes/finalizers
  verbs:
  - update
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - controlplanes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - etcds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - etcds/finalizers
  verbs:
  - update
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - etcds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - kubeadmconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - kubeadmconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - kubeadmconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - kubeadmconfigtemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - kubeadmconfigtemplates/finalizers
  verbs:
  - update
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - kubeadmconfigtemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - machinedeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - machinedeployments/finalizers
  verbs:
  - update
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - machinedeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - machines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - machines/finalizers
  verbs:
  - update
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - machines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - machinesets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - machinesets/finalizers
  verbs:
  - update
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - machinesets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - registries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - registries/finalizers
  verbs:
  - update
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - registries/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - workers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - workers/finalizers
  verbs:
  - update
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - workers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - logging.kubesphere.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - networking.istio.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - notification.kubesphere.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - policy
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - storage.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - storage.kubesphere.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - tenant.kubesphere.io
  resources:
  - '*'
  verbs:
  - '*'
